spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: task-server
  boot:
    admin:
      client:
        url: http://localhost:9090
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/task_server_schema
    username: batch_user
    password: batchuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: TaskScheduler
            instanceId: AUTO
          jobStore:
            isClustered: true
            clusterCheckinInterval: 10000
          job-store-type: JDBC
          jdbc:
            initialize-schema: NEVER
          properties:
            org.quartz.jobStore:
              tablePrefix: task_server_schema.QRTZ_
              driverDelegateClass: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            org.quartz.threadPool:
              threadNamePrefix: scheduler-worker
              threadCount: 25

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true  # Ensure built-in health checks like DB are enabled
    diskspace:
      enabled: true  # Enable diskspace health check
  endpoint:
    env:
      show-values: ALWAYS
      post:
        enabled: true
    configprops:
      show-values: ALWAYS
  info:
    env:
      enabled: true

server:
  port: 808

application:
  create-audit: false
  greeting:
    message: Hello
  refresh-message: TASK SERVER REFRESH MESSAGE '23:12'
  replica-number: 3
  config-server-health-url: ${application.config-server-base-url}/actuator/health
  data-provider-url: http://localhost:8087/api/user/v1

tasks:
  location: classpath:tasks/

logging:
  file:
    name: logs/task-server.log
  logback:
    rollingpolicy:
      max-file-size: 10MB

secondary:
  datasource:
    url: jdbc:mysql://localhost:3377/task_server_schema
    username: batch_user
    password: batchuser
    driver-class-name: com.mysql.cj.jdbc.Driver
