application:
  environment:
    name: prod
  appConfigs:
    config-batch: ${application.config-server-base-url}/config-batch/prod
    task-server: ${application.config-server-base-url}/task-server/prod
    refresh-batch: ${application.config-server-base-url}/refresh-batch/prod

  prod-message: '- - - - - - - - PRODUCTION CONFIG BATCH IS UP ND RUNNING ! ! ! - - - - - - - -'
